var simplemaps_usmap_mapdata = {
  main_settings: {
    //General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#444444",
    popups: "off",
    state_description: "",
    state_color: "#222222",
    state_hover_color: "#444444",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "no",

    //Location defaults
    location_description: "Add location markers using latitude and longitude!",
    location_color: "#2041D4",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#aaaaaa",
    label_hover_color: "#ffffff",
    label_size: 14,
    label_font: "Arial",
    hide_labels: "no",
    hide_eastern_labels: "no",
    manual_zoom: "no",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.1,

    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
    images_directory: "",
    fade_time: 0.1,
    import_labels: "no",
    link_text: "",
    state_image_url: "",
    state_image_position: "",
    location_image_url: "",
  },
  state_specific: {
    HI: {
      name: "Hawaii",
      url: "https://ballotstatus.hawaii.gov",
      description: "Hawaii Office of Elections",
    },
    AK: {
      name: "Alaska",
      url: "https://myvoterinformation.alaska.gov",
      description: "Alaska Division of Elections",
    },
    FL: {
      name: "Florida",
      url: "https://registration.elections.myflorida.com/CheckVoterStatus",
      description: "Florida Department of State",
    },
    NH: {
      name: "New Hampshire",
      url: "https://app.sos.nh.gov/Public/AbsenteeBallot.aspx",
      description:
        "New Hampshire Secretary of State, Voter Information Look-up",
    },
    VT: {
      name: "Vermont",
      url: "https://mvp.vermont.gov/",
      description: "Vermont Secretary of State, My Voter Page",
    },
    ME: {
      name: "Maine",
      url:
        "https://apps.web.maine.gov/cgi-bin/online/AbsenteeBallot/ballot_status.pl",
      description: "Maine Secretary of State",
    },
    RI: {
      name: "Rhode Island",
      url: "Rhode Island Department of State",
      description:
        "https://vote.sos.ri.gov/Home/UpdateVoterRecord?ActiveFlag=3",
    },
    NY: {
      name: "New York",
      url: "https://nysballot.elections.ny.gov/TrackMyBallot/Search",
      description: "New York State Board of Elections",
    },
    PA: {
      name: "Pennsylvania",
      url: "",
      description: "",
    },
    NJ: {
      name: "New Jersey",
      url: "",
      description: "",
    },
    DE: {
      name: "Delaware",
      url: "",
      description: "",
    },
    MD: {
      name: "Maryland",
      url: "",
      description: "",
    },
    VA: {
      name: "Virginia",
      url: "",
      description: "",
    },
    WV: {
      name: "West Virginia",
      url: "",
      description: "",
    },
    OH: {
      name: "Ohio",
      url: "",
      description: "",
    },
    IN: {
      name: "Indiana",
      url: "",
      description: "",
    },
    IL: {
      name: "Illinois",
      url: "",
      description: "",
    },
    CT: {
      name: "Connecticut",
      url: "",
      description: "",
    },
    WI: {
      name: "Wisconsin",
      url: "",
      description: "",
    },
    NC: {
      name: "North Carolina",
      url: "",
      description: "",
    },
    DC: {
      name: "District of Columbia",
      url: "",
      description: "",
    },
    MA: {
      name: "Massachusetts",
      url: "",
      description: "",
    },
    TN: {
      name: "Tennessee",
      url: "",
      description: "",
    },
    AR: {
      name: "Arkansas",
      url: "",
      description: "",
    },
    MO: {
      name: "Missouri",
      url: "",
      description: "",
    },
    GA: {
      name: "Georgia",
      url: "",
      description: "",
    },
    SC: {
      name: "South Carolina",
      url: "",
      description: "",
    },
    KY: {
      name: "Kentucky",
      url: "",
      description: "",
    },
    AL: {
      name: "Alabama",
      url: "",
      description: "",
    },
    LA: {
      name: "Louisiana",
      url: "",
      description: "",
    },
    MS: {
      name: "Mississippi",
      url: "",
      description: "",
    },
    IA: {
      name: "Iowa",
      url: "",
      description: "",
    },
    MN: {
      name: "Minnesota",
      url: "",
      description: "",
    },
    OK: {
      name: "Oklahoma",
      url: "",
      description: "",
    },
    TX: {
      name: "Texas",
      url: "",
      description: "",
    },
    NM: {
      name: "New Mexico",
      url: "",
      description: "",
    },
    KS: {
      name: "Kansas",
      url: "",
      description: "",
    },
    NE: {
      name: "Nebraska",
      url: "",
      description: "",
    },
    SD: {
      name: "South Dakota",
      url: "",
      description: "",
    },
    ND: {
      name: "North Dakota",
      url: "",
      description: "",
    },
    WY: {
      name: "Wyoming",
      url: "",
      description: "",
    },
    MT: {
      name: "Montana",
      url: "",
      description: "",
    },
    CO: {
      name: "Colorado",
      url: "",
      description: "",
    },
    UT: {
      name: "Utah",
      url: "",
      description: "",
    },
    AZ: {
      name: "Arizona",
      url: "",
      description: "",
    },
    NV: {
      name: "Nevada",
      url: "",
      description: "",
    },
    OR: {
      name: "Oregon",
      url: "",
      description: "",
    },
    WA: {
      name: "Washington",
      url: "",
      description: "",
    },
    CA: {
      name: "California",
      url: "",
      description: "",
    },
    MI: {
      name: "Michigan",
      url: "",
      description: "",
    },
    ID: {
      name: "Idaho",
      url: "",
      description: "",
    },
    GU: {
      name: "Guam",
      hide: "yes",
      url: "",
      description: "",
    },
    VI: {
      name: "Virgin Islands",
      hide: "yes",
      url: "",
      description: "",
    },
    PR: {
      name: "Puerto Rico",
      hide: "yes",
      url: "",
      description: "",
    },
    MP: {
      name: "Northern Mariana Islands",
      hide: "yes",
      url: "",
      description: "",
    },
    AS: {
      name: "American Samoa",
      hide: "yes",
      url: "",
      description: "",
    },
  },
  locations: {},
  labels: {
    NH: {
      parent_id: "NH",
      x: "932",
      y: "183",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    VT: {
      parent_id: "VT",
      x: "883",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    RI: {
      parent_id: "RI",
      x: "932",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    NJ: {
      parent_id: "NJ",
      x: "883",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    DE: {
      parent_id: "DE",
      x: "883",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    MD: {
      parent_id: "MD",
      x: "932",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    DC: {
      parent_id: "DC",
      x: "884",
      y: "332",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    MA: {
      parent_id: "MA",
      x: "932",
      y: "213",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    CT: {
      parent_id: "CT",
      x: "932",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    HI: {
      parent_id: "HI",
      x: 305,
      y: 565,
      pill: "yes",
      url: "",
      description: "",
    },
    AK: {
      parent_id: "AK",
      x: "113",
      y: "495",
      url: "",
      description: "",
    },
    FL: {
      parent_id: "FL",
      x: "773",
      y: "510",
      url: "",
      description: "",
    },
    ME: {
      parent_id: "ME",
      x: "893",
      y: "85",
      url: "",
      description: "",
    },
    NY: {
      parent_id: "NY",
      x: "815",
      y: "158",
      url: "",
      description: "",
    },
    PA: {
      parent_id: "PA",
      x: "786",
      y: "210",
      url: "",
      description: "",
    },
    VA: {
      parent_id: "VA",
      x: "790",
      y: "282",
      url: "",
      description: "",
    },
    WV: {
      parent_id: "WV",
      x: "744",
      y: "270",
      url: "",
      description: "",
    },
    OH: {
      parent_id: "OH",
      x: "700",
      y: "240",
      url: "",
      description: "",
    },
    IN: {
      parent_id: "IN",
      x: "650",
      y: "250",
      url: "",
      description: "",
    },
    IL: {
      parent_id: "IL",
      x: "600",
      y: "250",
      url: "",
      description: "",
    },
    WI: {
      parent_id: "WI",
      x: "575",
      y: "155",
      url: "",
      description: "",
    },
    NC: {
      parent_id: "NC",
      x: "784",
      y: "326",
      url: "",
      description: "",
    },
    TN: {
      parent_id: "TN",
      x: "655",
      y: "340",
      url: "",
      description: "",
    },
    AR: {
      parent_id: "AR",
      x: "548",
      y: "368",
      url: "",
      description: "",
    },
    MO: {
      parent_id: "MO",
      x: "548",
      y: "293",
      url: "",
      description: "",
    },
    GA: {
      parent_id: "GA",
      x: "718",
      y: "405",
      url: "",
      description: "",
    },
    SC: {
      parent_id: "SC",
      x: "760",
      y: "371",
      url: "",
      description: "",
    },
    KY: {
      parent_id: "KY",
      x: "680",
      y: "300",
      url: "",
      description: "",
    },
    AL: {
      parent_id: "AL",
      x: "655",
      y: "405",
      url: "",
      description: "",
    },
    LA: {
      parent_id: "LA",
      x: "550",
      y: "435",
      url: "",
      description: "",
    },
    MS: {
      parent_id: "MS",
      x: "600",
      y: "405",
      url: "",
      description: "",
    },
    IA: {
      parent_id: "IA",
      x: "525",
      y: "210",
      url: "",
      description: "",
    },
    MN: {
      parent_id: "MN",
      x: "506",
      y: "124",
      url: "",
      description: "",
    },
    OK: {
      parent_id: "OK",
      x: "460",
      y: "360",
      url: "",
      description: "",
    },
    TX: {
      parent_id: "TX",
      x: "425",
      y: "435",
      url: "",
      description: "",
    },
    NM: {
      parent_id: "NM",
      x: "305",
      y: "365",
      url: "",
      description: "",
    },
    KS: {
      parent_id: "KS",
      x: "445",
      y: "290",
      url: "",
      description: "",
    },
    NE: {
      parent_id: "NE",
      x: "420",
      y: "225",
      url: "",
      description: "",
    },
    SD: {
      parent_id: "SD",
      x: "413",
      y: "160",
      url: "",
      description: "",
    },
    ND: {
      parent_id: "ND",
      x: "416",
      y: "96",
      url: "",
      description: "",
    },
    WY: {
      parent_id: "WY",
      x: "300",
      y: "180",
      url: "",
      description: "",
    },
    MT: {
      parent_id: "MT",
      x: "280",
      y: "95",
      url: "",
      description: "",
    },
    CO: {
      parent_id: "CO",
      x: "320",
      y: "275",
      url: "",
      description: "",
    },
    UT: {
      parent_id: "UT",
      x: "223",
      y: "260",
      url: "",
      description: "",
    },
    AZ: {
      parent_id: "AZ",
      x: "205",
      y: "360",
      url: "",
      description: "",
    },
    NV: {
      parent_id: "NV",
      x: "140",
      y: "235",
      url: "",
      description: "",
    },
    OR: {
      parent_id: "OR",
      x: "100",
      y: "120",
      url: "",
      description: "",
    },
    WA: {
      parent_id: "WA",
      x: "130",
      y: "55",
      url: "",
      description: "",
    },
    ID: {
      parent_id: "ID",
      x: "200",
      y: "150",
      url: "",
      description: "",
    },
    CA: {
      parent_id: "CA",
      x: "79",
      y: "285",
      url: "",
      description: "",
    },
    MI: {
      parent_id: "MI",
      x: "663",
      y: "185",
      url: "",
      description: "",
    },
    PR: {
      parent_id: "PR",
      x: "620",
      y: "545",
      url: "",
      description: "",
    },
    GU: {
      parent_id: "GU",
      x: "550",
      y: "540",
      url: "",
      description: "",
    },
    VI: {
      parent_id: "VI",
      x: "680",
      y: "519",
      url: "",
      description: "",
    },
    MP: {
      parent_id: "MP",
      x: "570",
      y: "575",
      url: "",
      description: "",
    },
    AS: {
      parent_id: "AS",
      x: "665",
      y: "580",
      url: "",
      description: "",
    },
  },
  regions: {
    0: {
      states: ["DC", "NH", "MA", "CT", "RI", "MD", "VT", "NJ", "DE"],
      name: "Northeast",
      url: "",
      description: "",
    },
  },
};
