var simplemaps_usmap_mapdata = {
  main_settings: {
    //General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#444444",
    popups: "off",
    state_description: "",
    state_color: "#222222",
    state_hover_color: "#444444",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "no",

    //Location defaults
    location_description: "Add location markers using latitude and longitude!",
    location_color: "#2041D4",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#aaaaaa",
    label_hover_color: "#ffffff",
    label_size: 14,
    label_font: "Arial",
    hide_labels: "no",
    hide_eastern_labels: "no",
    manual_zoom: "no",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.1,

    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
    images_directory: "",
    fade_time: 0.1,
    import_labels: "no",
    link_text: "",
    state_image_url: "",
    state_image_position: "",
    location_image_url: "",
  },

  // prettier-ignore
  state_specific: {
    AK: {
      name: "Alaska",
      url: "https://myvoterinformation.alaska.gov",
      description: "Alaska Division of Elections",
    },
    AL: {
      name: "Alabama",
      url: "https://myinfo.alabamavotes.gov/voterview",
      description: "Alabama Votes",
    },
    AR: {
      name: "Arkansas",
      url: "https://www.voterview.ar-nova.org/VoterView",
      description: "Arkansas Secretary of State",
    },
    AS: {
      name: "American Samoa",
      hide: "yes",
      url: "",
      description: "",
    },
    AZ: {
      name: "Arizona",
      url: "https://my.arizona.vote/AbsenteeTracker.aspx",
      description: "Arizona Secretary of State, Voter Information Portal",
    },
    CA: {
      name: "California",
      url: "https://california.ballottrax.net/voter/",
      description: "California Secretary of State, Where's My Ballot?",
    },
    CO: {
      name: "Colorado",
      url: "https://colorado.ballottrax.net/voter/",
      description: "Colorado Ballottrax",
    },
    CT: {
      name: "Connecticut",
      url: "https://portaldir.ct.gov/sots/LookUp.aspx",
      description: "Connecticut Secretary of State",
    },
    DC: {
      name: "District of Columbia",
      url: "https://www.dcboe.org/Voters/Absentee-Voting/Track-Absentee-Ballot",
      description: "District of Columbia Board of Elections",
    },
    DE: {
      name: "Delaware",
      url: "https://ivote.de.gov/VoterView",
      description: "Delaware Department of Elections",
    },
    FL: {
      name: "Florida",
      url: "https://registration.elections.myflorida.com/CheckVoterStatus",
      description: "Florida Department of State",
    },
    GA: {
      name: "Georgia",
      url: "https://www.mvp.sos.ga.gov",
      description: "Georgia Secretary of State, My Voter Page",
    },
    GU: {
      name: "Guam",
      hide: "yes",
      url: "",
      description: "",
    },
    HI: {
      name: "Hawaii",
      url: "https://ballotstatus.hawaii.gov",
      description: "Hawaii Office of Elections",
    },
    IA: {
      name: "Iowa",
      url: "https://sos.iowa.gov/elections/absenteeballotstatus/absentee/search",
      description: "Iowa Secretary of State",
    },
    ID: {
      name: "Idaho",
      url: "https://elections.sos.idaho.gov/ElectionLink/ElectionLink/VoterSearch.aspx",
      description: "Idaho Secretary of State",
    },
    IL: {
      name: "Illinois",
      url: "https://elections.il.gov/VotingAndRegistrationSystems/ProvisionalBallotSearch.aspx",
      description: "Provisional Ballots only",
    },
    IN: {
      name: "Indiana",
      url: "https://indianavoters.in.gov",
      description: "Indiana Secretary of State, Voter Portal",
    },
    KS: {
      name: "Kansas",
      url: "https://myvoteinfo.voteks.org/voterview",
      description: "Kansas Secretary of State, VoterView",
    },
    KY: {
      name: "Kentucky",
      url: "https://vrsws.sos.ky.gov/vic/",
      description: "Kentucky State Board of Elections",
    },
    LA: {
      name: "Louisiana",
      url: "https://voterportal.sos.la.gov",
      description: "Louisiana Secretary of State, Geaux Vote",
    },
    MA: {
      name: "Massachusetts",
      url: "https://www.sec.state.ma.us/wheredoivotema/track/trackmyballot.aspx",
      description: "Secretary of the Commonwealth of Massachusetts",
    },
    MD: {
      name: "Maryland",
      url: "https://voterservices.elections.maryland.gov/VoterSearch",
      description: "Maryland Board of Elections",
    },
    ME: {
      name: "Maine",
      url: "https://apps.web.maine.gov/cgi-bin/online/AbsenteeBallot/ballot_status.pl",
      description: "Maine Secretary of State",
    },
    MI: {
      name: "Michigan",
      url: "https://mvic.sos.state.mi.us/Voter/Index",
      description: "Michigan Department of State, Voter Information Center",
    },
    MN: {
      name: "Minnesota",
      url: "https://mnvotes.sos.state.mn.us/AbsenteeBallotStatus.aspx",
      description: "Minnesota Secretary of State",
    },
    MO: {
      name: "Missouri",
      url: "https://movotesportal.sos.mo.gov/movotes/voter/login.aspx",
      description: "Military only",
    },
    MP: {
      name: "Northern Mariana Islands",
      hide: "yes",
      url: "",
      description: "",
    },
    MS: {
      name: "Mississippi",
      url: "https://www.sos.ms.gov/MSCountyElectionInfo/",
      description: "You can check the status of your absentee ballot by contacting your election official",
    },
    MT: {
      name: "Montana",
      url: "https://app.mt.gov/voterinfo/",
      description: "My Voter Page",
    },
    NC: {
      name: "North Carolina",
      url: "https://northcarolina.ballottrax.net/voter/",
      description: "North Carolina State Board of Elections, Ballottrax",
    },
    ND: {
      name: "North Dakota",
      url: "https://vip.sos.nd.gov/AbsenteeTracker.aspx",
      description: "North Dakota Secretary of State",
    },
    NE: {
      name: "Nebraska",
      url: "https://www.votercheck.necvr.ne.gov/voterview",
      description: "Nebraska Voter Information Lookup",
    },
    NH: {
      name: "New Hampshire",
      url: "https://app.sos.nh.gov/Public/AbsenteeBallot.aspx",
      description: "New Hampshire Secretary of State, Voter Information Look-up",
    },
    NJ: {
      name: "New Jersey",
      url: "https://www.nj.gov/state/elections/vote-track-my-ballot.shtml",
      description: "New Jersey Voter Information Portal",    
    },
    NM: {
      name: "New Mexico",
      url: "https://voterportal.servis.sos.state.nm.us/WhereToVote.aspx?tab=AbsenteeTracker",
      description: "New Mexico Secretary of State",
    },
    NV: {
      name: "Nevada",
      url: "https://www.nvsos.gov/votersearch/",
      description: "Nevada Secretary of State",
    },
    NY: {
      name: "New York",
      url: "https://nysballot.elections.ny.gov/TrackMyBallot/Search",
      description: "New York State Board of Elections",
    },
    OH: {
      name: "Ohio",
      url: "https://www.sos.state.oh.us/elections/voters/toolkit/ballot-tracking/",
      description: "Ohio Secretary of State (each county has its own tool)",
    },
    OK: {
      name: "Oklahoma",
      url: "https://okvoterportal.okelections.us",
      description: "Oklahoma State Election Board, OK Voter Portal",
    },
    OR: {
      name: "Oregon",
      url: "https://secure.sos.state.or.us/orestar/vr/showVoterSearch.do",
      description: "Oregon Secretary of State",
    },
    PA: {
      name: "Pennsylvania",
      url: "https://www.pavoterservices.pa.gov/Pages/BallotTracking.aspx",
      description: "Pennsylvania Department of State",
    },
    PR: {
      name: "Puerto Rico",
      hide: "yes",
      url: "",
      description: "",
    },
    RI: {
      name: "Rhode Island",
      url: "https://vote.sos.ri.gov/Home/UpdateVoterRecord?ActiveFlag=3",
      description: "Rhode Island Department of State",
    },
    SC: {
      name: "South Carolina",
      url: "https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx?PageMode=AbsenteeInfo",
      description: "South Carolina Election Commission",
    },
    SD: {
      name: "South Dakota",
      url: "https://vip.sdsos.gov/VIPLogin.aspx",
      description: "South Dakota Secretary of State",
    },
    TN: {
      name: "Tennessee",
      url: "https://tnmap.tn.gov/voterlookup/",
      description: "Tennessee Secretary of State",
    },
    TX: {
      name: "Texas",
      url: "https://webservices.sos.state.tx.us/FPCA/index.aspx",
      description: "Military only (FPCA Ballot Tracker)",
    },
    UT: {
      name: "Utah",
      url: "https://votesearch.utah.gov/voter-search/search/search-by-voter/track-mail-ballot",
      description: "Utah Lt. Govenor, Track My Ballot",
    },
    VA: {
      name: "Virginia",
      url: "https://ballotscout.org/partners/5a8f1161-23a0-4fa0-8ec9-3e090e97e9b3/va-search",
      description: "Commonwealth of Virginia, Ballot Scout",
    },
    VI: {
      name: "Virgin Islands",
      hide: "yes",
      url: "",
      description: "",
    },
    VT: {
      name: "Vermont",
      url: "https://mvp.vermont.gov/",
      description: "Vermont Secretary of State, My Voter Page",
    },
    WA: {
      name: "Washington",
      url: "https://voter.votewa.gov/WhereToVote.aspx",
      description: "Vote WA",    
    },
    WI: {
      name: "Wisconsin",
      url: "https://myvote.wi.gov/en-us/TrackMyBallot",
      description: "MyVote Wisconsin",
    },
    WV: {
      name: "West Virginia",
      url: "https://services.sos.wv.gov/Elections/Voter/AbsenteeBallotTracking",
      description: "West Virginia Secretary of State",
    },
    WY: {
      name: "Wyoming",
      url: "https://sos.wyo.gov/Elections/Docs/WYCountyClerks_AbsRequest_VRChange.pdf",
      description: "Email county clerk",
    },
  },
  locations: {},
  labels: {
    NH: {
      parent_id: "NH",
      x: "932",
      y: "183",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    VT: {
      parent_id: "VT",
      x: "883",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    RI: {
      parent_id: "RI",
      x: "932",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    NJ: {
      parent_id: "NJ",
      x: "883",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    DE: {
      parent_id: "DE",
      x: "883",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    MD: {
      parent_id: "MD",
      x: "932",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    DC: {
      parent_id: "DC",
      x: "884",
      y: "332",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    MA: {
      parent_id: "MA",
      x: "932",
      y: "213",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    CT: {
      parent_id: "CT",
      x: "932",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
      url: "",
      description: "",
    },
    HI: {
      parent_id: "HI",
      x: 305,
      y: 565,
      pill: "yes",
      url: "",
      description: "",
    },
    AK: {
      parent_id: "AK",
      x: "113",
      y: "495",
      url: "",
      description: "",
    },
    FL: {
      parent_id: "FL",
      x: "773",
      y: "510",
      url: "",
      description: "",
    },
    ME: {
      parent_id: "ME",
      x: "893",
      y: "85",
      url: "",
      description: "",
    },
    NY: {
      parent_id: "NY",
      x: "815",
      y: "158",
      url: "",
      description: "",
    },
    PA: {
      parent_id: "PA",
      x: "786",
      y: "210",
      url: "",
      description: "",
    },
    VA: {
      parent_id: "VA",
      x: "790",
      y: "282",
      url: "",
      description: "",
    },
    WV: {
      parent_id: "WV",
      x: "744",
      y: "270",
      url: "",
      description: "",
    },
    OH: {
      parent_id: "OH",
      x: "700",
      y: "240",
      url: "",
      description: "",
    },
    IN: {
      parent_id: "IN",
      x: "650",
      y: "250",
      url: "",
      description: "",
    },
    IL: {
      parent_id: "IL",
      x: "600",
      y: "250",
      url: "",
      description: "",
    },
    WI: {
      parent_id: "WI",
      x: "575",
      y: "155",
      url: "",
      description: "",
    },
    NC: {
      parent_id: "NC",
      x: "784",
      y: "326",
      url: "",
      description: "",
    },
    TN: {
      parent_id: "TN",
      x: "655",
      y: "340",
      url: "",
      description: "",
    },
    AR: {
      parent_id: "AR",
      x: "548",
      y: "368",
      url: "",
      description: "",
    },
    MO: {
      parent_id: "MO",
      x: "548",
      y: "293",
      url: "",
      description: "",
    },
    GA: {
      parent_id: "GA",
      x: "718",
      y: "405",
      url: "",
      description: "",
    },
    SC: {
      parent_id: "SC",
      x: "760",
      y: "371",
      url: "",
      description: "",
    },
    KY: {
      parent_id: "KY",
      x: "680",
      y: "300",
      url: "",
      description: "",
    },
    AL: {
      parent_id: "AL",
      x: "655",
      y: "405",
      url: "",
      description: "",
    },
    LA: {
      parent_id: "LA",
      x: "550",
      y: "435",
      url: "",
      description: "",
    },
    MS: {
      parent_id: "MS",
      x: "600",
      y: "405",
      url: "",
      description: "",
    },
    IA: {
      parent_id: "IA",
      x: "525",
      y: "210",
      url: "",
      description: "",
    },
    MN: {
      parent_id: "MN",
      x: "506",
      y: "124",
      url: "",
      description: "",
    },
    OK: {
      parent_id: "OK",
      x: "460",
      y: "360",
      url: "",
      description: "",
    },
    TX: {
      parent_id: "TX",
      x: "425",
      y: "435",
      url: "",
      description: "",
    },
    NM: {
      parent_id: "NM",
      x: "305",
      y: "365",
      url: "",
      description: "",
    },
    KS: {
      parent_id: "KS",
      x: "445",
      y: "290",
      url: "",
      description: "",
    },
    NE: {
      parent_id: "NE",
      x: "420",
      y: "225",
      url: "",
      description: "",
    },
    SD: {
      parent_id: "SD",
      x: "413",
      y: "160",
      url: "",
      description: "",
    },
    ND: {
      parent_id: "ND",
      x: "416",
      y: "96",
      url: "",
      description: "",
    },
    WY: {
      parent_id: "WY",
      x: "300",
      y: "180",
      url: "",
      description: "",
    },
    MT: {
      parent_id: "MT",
      x: "280",
      y: "95",
      url: "",
      description: "",
    },
    CO: {
      parent_id: "CO",
      x: "320",
      y: "275",
      url: "",
      description: "",
    },
    UT: {
      parent_id: "UT",
      x: "223",
      y: "260",
      url: "",
      description: "",
    },
    AZ: {
      parent_id: "AZ",
      x: "205",
      y: "360",
      url: "",
      description: "",
    },
    NV: {
      parent_id: "NV",
      x: "140",
      y: "235",
      url: "",
      description: "",
    },
    OR: {
      parent_id: "OR",
      x: "100",
      y: "120",
      url: "",
      description: "",
    },
    WA: {
      parent_id: "WA",
      x: "130",
      y: "55",
      url: "",
      description: "",
    },
    ID: {
      parent_id: "ID",
      x: "200",
      y: "150",
      url: "",
      description: "",
    },
    CA: {
      parent_id: "CA",
      x: "79",
      y: "285",
      url: "",
      description: "",
    },
    MI: {
      parent_id: "MI",
      x: "663",
      y: "185",
      url: "",
      description: "",
    },
    PR: {
      parent_id: "PR",
      x: "620",
      y: "545",
      url: "",
      description: "",
    },
    GU: {
      parent_id: "GU",
      x: "550",
      y: "540",
      url: "",
      description: "",
    },
    VI: {
      parent_id: "VI",
      x: "680",
      y: "519",
      url: "",
      description: "",
    },
    MP: {
      parent_id: "MP",
      x: "570",
      y: "575",
      url: "",
      description: "",
    },
    AS: {
      parent_id: "AS",
      x: "665",
      y: "580",
      url: "",
      description: "",
    },
  },
  regions: {
    0: {
      states: ["DC", "NH", "MA", "CT", "RI", "MD", "VT", "NJ", "DE"],
      name: "Northeast",
      url: "",
      description: "",
    },
  },
};
